server:
  port: 8080
  servlet:
    context-path: /countdown

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

lodsve:
  countdown:
    enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
