server:
  port: 8080
  servlet:
    context-path: /mybatis

lodsve:
  rdbms:
    default-data-source-name: demo
    data-source:
      demo:
        pool-name: demo-datasource
        type: com.zaxxer.hikari.HikariDataSource
        url: ENC(x1bFCNX7T4k+7uLfWVGLIH+DPgwx8rg4far0JMDliNOLkNPesItSd4qLEzaFaa8/raLwyEa5Z2hEWVbj+sB8FgXIaR8/ZEN2Kn7kIisByL33H2hQag0QHVCo86xVVpWgg8kl9C8fn87dg3VX7H4u7WFfV7zKO1Wf)
        username: ENC(eAG075KdBNedlgERYooGQw==)
        password: ENC(9grKPK7WGNyLe9REuniI0Iw7qg4pY2nC)
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 初始化连接数量
        initial-size: 5
        # 最小空闲连接数
        min-idle: 10
        # 最大并发连接数
        max-active: 20
        hikari:
          maximum-pool-size: 10
      test:
        pool-name: test-datasource
        type: com.alibaba.druid.pool.DruidDataSource
        url: ENC(h2V9lOIm4IhCYJW9snHwVUBA9mIf21PdX62jg4K84eqTMmnqh2fR5GNwUq02RArCbWUqJmjvwxIMwgHkX8dY7x/AoitTT6MptMuxX78Vh4hf7nnhRy81FIukNKn32KJovJV6+dCkfXDgfOLJvQQOWm2EJOG/4tBV)
        username: ENC(eAG075KdBNedlgERYooGQw==)
        password: ENC(9grKPK7WGNyLe9REuniI0Iw7qg4pY2nC)
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          maximum-pool-size: 10
        druid:
          max-active: 10
    druid:
      filter:
        #监控统计用的filter
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 5000
        #防御sql注入的filter
        wall:
          enabled: true
          config:
            multi-statement-allow: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: druid
  mybatis:
    map-underscore-to-camel-case: true
  swagger:
    enabled: true
    title: Mybatis示例工程接口文档
    description: 这是一个Mybatis示例工程，用来展示如何使用Mybatis
    license: GPL-3.0
    license-url: https://opensource.org/licenses/GPL-3.0
    terms-of-service-url: https://www.crazy-coder.cn
    version: V1.0.0-SNAPSHOT
    contact:
      name: 孙昊
      url: https://www.crazy-coder.cn
      email: sunhao.java@gmail.com

