name: Deploy Snapshot Weekly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 0'

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup JDK1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Version
        run: |
          MVN_VERSION=$(mvn -q -N -Dexec.executable="echo"  -Dexec.args='${project.version}'  org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
          echo $VERSION | grep -q -E '\-SNAPSHOT$' && echo true || exit 1
